# Generated by Django 5.1.3 on 2024-11-26 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_price", models.FloatField(default=0.0)),
                (
                    "payment",
                    models.BooleanField(default=False, help_text="Оплачен ли заказ"),
                ),
                (
                    "docs",
                    models.ForeignKey(
                        help_text="Документ для анализа",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docs.docs",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
